- name: Install Docker on ec2
  hosts: remote_machine
  become: true
  tasks:
    - name: Install Docker
      yum:
        name:
          - docker
        state: present
    - name: start docker service
      systemd:
        name: docker
        state: started
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
    - name: Copy docker-app directory to machine
      ansible.builtin.copy:
        src: ./docker-app/
        dest: /home/ec2-user/docker-app/
    - name: Build Docker image
      community.docker.docker_image:
        name: node-app
        build:
          path: /home/ec2-user/docker-app/
        source: build
        push: false
    - name: Run Docker container
      community.docker.docker_container:
        name: node-container
        image: node-app
        state: started
        ports:
          - "3000:3000"
